export const GET_EXAMPLE = "GET_EXAMPLE"

export const GET_EXAMPLE_SUCCESS = "GET_EXAMPLE_SUCCESS"

export const GET_EXAMPLE_ERROR = "GET_EXAMPLE_ERROR"

export const GET_EXAMPLE_DETAILS = "GET_EXAMPLE_DETAILS"

export const GET_EXAMPLE_DETAILS_SUCCESS = "GET_EXAMPLE_DETAILS_SUCCESS"

export const GET_EXAMPLE_DETAILS_ERROR = "GET_EXAMPLE_DETAILS_ERROR"

export const ADD_EXAMPLE = "ADD_EXAMPLE"

export const ADD_EXAMPLE_SUCCESS = "ADD_EXAMPLE_SUCCESS"

export const ADD_EXAMPLE_ERROR = "ADD_EXAMPLE_ERROR"

export const UPDATE_EXAMPLE = "UPDATE_EXAMPLE"

export const UPDATE_EXAMPLE_SUCCESS = "UPDATE_EXAMPLE_SUCCESS"

export const UPDATE_EXAMPLE_ERROR = "UPDATE_EXAMPLE_ERROR"

export const DELETE_EXAMPLE = "DELETE_EXAMPLE"

export const DELETE_EXAMPLE_SUCCESS = "DELETE_EXAMPLE_SUCCESS"

export const DELETE_EXAMPLE_ERROR = "DELETE_EXAMPLE_ERROR"

export const CHANGE_LIMIT = "CHANGE_LIMIT"

export const CHANGE_SKIP = "CHANGE_SKIP"

export const CHANGE_PAGE = "CHANGE_PAGE"
