export const GET_BOOKS = "GET_BOOKS"

export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS"

export const GET_BOOKS_ERROR = "GET_BOOKS_ERROR"

export const GET_BOOKS_DETAILS = "GET_BOOKS_DETAILS"

export const GET_BOOKS_DETAILS_SUCCESS = "GET_BOOKS_DETAILS_SUCCESS"

export const GET_BOOKS_DETAILS_ERROR = "GET_BOOKS_DETAILS_ERROR"

export const ADD_BOOKS = "ADD_BOOKS"

export const ADD_BOOKS_SUCCESS = "ADD_BOOKS_SUCCESS"

export const ADD_BOOKS_ERROR = "ADD_BOOKS_ERROR"

export const UPDATE_BOOKS = "UPDATE_BOOKS"

export const UPDATE_BOOKS_SUCCESS = "UPDATE_BOOKS_SUCCESS"

export const UPDATE_BOOKS_ERROR = "UPDATE_BOOKS_ERROR"

export const DELETE_BOOKS = "DELETE_BOOKS"

export const DELETE_BOOKS_SUCCESS = "DELETE_BOOKS_SUCCESS"

export const DELETE_BOOKS_ERROR = "DELETE_BOOKS_ERROR"

export const CHANGE_LIMIT = "CHANGE_LIMIT"

export const CHANGE_SKIP = "CHANGE_SKIP"

export const CHANGE_PAGE = "CHANGE_PAGE"
