export const GET_USERS = "GET_USERS"

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"

export const GET_USERS_ERROR = "GET_USERS_ERROR"

export const GET_USERS_DETAILS = "GET_USERS_DETAILS"

export const GET_USERS_DETAILS_SUCCESS = "GET_USERS_DETAILS_SUCCESS"

export const GET_USERS_DETAILS_ERROR = "GET_USERS_DETAILS_ERROR"

export const ADD_USERS = "ADD_USERS"

export const ADD_USERS_SUCCESS = "ADD_USERS_SUCCESS"

export const ADD_USERS_ERROR = "ADD_USERS_ERROR"

export const UPDATE_USERS = "UPDATE_USERS"

export const UPDATE_USERS_SUCCESS = "UPDATE_USERS_SUCCESS"

export const UPDATE_USERS_ERROR = "UPDATE_USERS_ERROR"

export const DELETE_USERS = "DELETE_USERS"

export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS"

export const DELETE_USERS_ERROR = "DELETE_USERS_ERROR"

export const CHANGE_LIMIT = "CHANGE_LIMIT"

export const CHANGE_SKIP = "CHANGE_SKIP"

export const CHANGE_PAGE = "CHANGE_PAGE"
